# Generated by Django 4.2.1 on 2023-12-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birthday', models.DateField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('tg_username', models.TextField(null=True)),
                ('id_card_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.TextField()),
                ('is_master', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.auditorium')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.employee')),
            ],
        ),
        migrations.CreateModel(
            name='KeyTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_time', models.DateTimeField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.auditorium')),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_employee', to='keycontrol.employee')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_employee', to='keycontrol.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.role'),
        ),
        migrations.CreateModel(
            name='ByEmployeeTakedKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('take_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('is_returned', models.BooleanField()),
                ('key_transferred', models.BooleanField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.auditorium')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keycontrol.employee')),
            ],
        ),
    ]
